### ISSUE TITLE
依存性検索時にマイグレーションナレッジやpom.xml も移植対象ファイルとして表示されている

### ISSUE THREAD

**Issue by kyohei-nakamura** [TUBAME/migration-tool#75]

**Comment by azkaoru** [comment]
http://tubame.github.io/ja/wsearch/wsearch.html
にある検索対象のフィルターで、検索除外したいXMLを指定する方法があるので、基本的にはフィルター設定を行ってほしいが、いかがでしょうか？

**Comment by kyohei-nakamura** [comment]
修正バージョンで依存性検索を実行したところ、以下の結果が出力されました。  

```
"error","Xml","","(unknown)","-","http://maven.apache.org/xsd/maven-4.0.0.xsd","pom.xml","1","移植先に存在しません",""
"error","Xml","","(unknown)","-","http://maven.apache.org/xsd/maven-4.0.0.xsd","target\m2e-wtp\web-resources\META-INF\maven\tubame.example\tomcat80to85-app\pom.xml","1","移植先に存在しません",""
```

こちらは今回の修正の対象外になりますでしょうか。  
また、フィルタ設定にて除外したい場合、正規表現としてどのような値を設定すればよいかご教示いただけますでしょうか。

**Comment by azkaoru** [comment]
今回の修正の範囲内です。

https://github.com/azkaoru/migration-tool/commit/aaaa0fb5376af2eeed1951a7a9dd14d7c07d8dd5

上記のコミットより、依存性検索のプリファレンス設定で、xmlの除外フィルターが適用されると思っていました。

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
```
上記のpom.xmlを検索対象に入れて、検索しましたが、こちらの環境では、errorとして検知されませんでした。
