### ISSUE TITLE
改行を含むと、依存性検索のチェックリスト情報ビューになにも表示されない。

### ISSUE THREAD

**Issue by azkaoru** [TUBAME/migration-tool#80]
ナレッジ管理ツールで検索手順に改行を含む場合、依存性検索のチェックリスト情報ビューの検索手順は何も表示されない。

**Comment by azkaoru** [comment]
ナレッジ管理ツールで検索手順に改行を含む場合も、チェックリスト情報ビューで表示されることを確認した。

**Comment by TUBAME** [comment]
fix tubame 1.1.1
