### ISSUE TITLE
search fail using Struts1ToSpringMVC.xml ,if struts-config.xml not exist

### ISSUE THREAD

**Issue by azkaoru** [TUBAME/migration-tool#82]
Struts1ToSpringMVC.xml is defiend that search struts-config.xml
Currently we workaround that,rename filename(struts-config.xml) ,if another struts-config file exists

**Comment by azkaoru** [comment]
struts-config.xmlが存在しない場合も、ただしく検索できることを確認した。

**Comment by TUBAME** [comment]
fix tubame 1.1.1
